console.log("create stripe1.model.js");
console.log("update after create stripe2.model.js");
console.log("Login");
console.log("Logout");
console.log("conflict 1");
console.log("conflict 2");
console.log("conflict 3");
console.log("conflict 4");
console.log("conflict 5");
console.log("conflict 6");
console.log("conflict 7");
console.log("conflict 8");
console.log("conflict 9");
console.log("conflict 10");
